### ISSUE TITLE
Complete the google polymer tutorial

### ISSUE THREAD

**Issue by JoshuaVSherman** [UltimatePromotions/tipsylift#29]

**Comment by JoshuaVSherman** [comment]
Acceptance Criteria: create your own training repo under Ultimate Promotions and push some code there (that runs Polymer elements), use this tutorial https://www.polymer-project.org/1.0/start/first-element/intro
then wait for a code review

**Comment by TheR3dErik** [comment]
So you want me to make an entirely new repository under "Ultimate Promotions" for training? Ok.

**Comment by JoshuaVSherman** [comment]
Yep use it for practice that's great

**Comment by TheR3dErik** [comment]
Now it's done!

**Comment by JoshuaVSherman** [comment]
Awesome, let me know when you have the picture slideshow working
