### ISSUE TITLE
Authentication using Aurelia-auth and Google 

### ISSUE THREAD

**Issue by chemmom2** [UltimatePromotions/tipsylift#30]
https://github.com/paulvanbladel/aurelia-auth

https://shellmonger.com/2015/07/12/using-authentication-in-an-aurelia-app/

https://www.npmjs.com/package/aurelia-auth

https://libraries.io/github/devscott/aurelia-auth

https://github.com/sahat/satellizer/#usage

https://console.developers.google.com/apis/dashboard?project=tipsyryde&authuser=1

https://console.developers.google.com/apis/credentials/domainverification?project=tipsyryde&authuser=0

**Comment by JoshuaVSherman** [comment]
Issue moved to [UltimatePromotions/ourhandsandfeet #16](https://github.com/UltimatePromotions/ourhandsandfeet/issues/16) via [**ZenHub**](https://www.zenhub.com/)
