### ISSUE TITLE
Eric demonstrates understanding of Gitflow

### ISSUE THREAD

**Issue by chemmom2** [UltimatePromotions/tipsylift#41]
Acceptance Criteria:
1. Create your own branch from Master. (Note: Be sure your branch always has the most up-to-date version of Master to avoid conflict errors.)
2. Pull the code down to your branch.
3. Write a short paragraph biography of yourself and insert it into the "Read Me" file.
4. Push your new code to your branch in Github.
5. Initiate a pull request to Master.
6. Wait for code review.

**Comment by TheR3dErik** [comment]
Did this, I am going to close this issue for now...
